### PR TITLE
New command: grab

### PR DESCRIPTION
**Pull request by byeugenius**
### A new path to libraries
The original path to the libraries was changed from **/root** to **/root/Scripts** in order to avoid a mess in the root folder

### New command: grab
This command allows you to automate the process of finding and decrypting passwd, Bank.txt, Mail.txt

> The syntax is as follows: `grab [a/p/b/m]`
> If the parameter is not declared, mode "a" (all files) will be automatically selected
> If the parameter is declared, then the mode will be appropriate: p - passwd, b - banks, m - mails

### CODE REVIEW

**Comment by byeugenius** [comment]
### Known bugs (or features)
- [ ] When decrypting passwd, only the first credentials are decrypted - usually the root data

**Comment by h4cktoria** [comment]
Hello there. Thanks for your pull request. Everything seems fine, but new path to the sources bothers me. Maybe change it to something like **/root/Scripts/Lunarium** or **/root/Lunarium**?

**Comment by byeugenius** [comment]
Yes, you're right. I will change the path, fix bugs, add a little beauty to the output. Should I close my request? Or let it stay open until I'm done with the edits?

**Comment by h4cktoria** [comment]
Let it stay opened until you are done. Thanks for the effort. Can't wait!

**Comment by cloverrfoxx** [comment]
> ### Known bugs (or features)
> * [ ]  When decrypting passwd, only the first credentials are decrypted - usually the root data

intentional, you're supposed to use the method `cat /etc/passwd | grep username | crack` to decipher a specific password, but good point

**Pull request merged**
